services:
  bidb:
    platform: 'linux/amd64'
    container_name: bidb
    build:
      context: ./docker
      dockerfile: mysql/Dockerfile
    volumes:
      - db_data_bi:/var/lib/mysql:cached
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: happybeer
      MYSQL_DATABASE: bidb
      MYSQL_USER: staff
      MYSQL_PASSWORD: happybeer
    ports:
      - "33060:3306"
  mbdb:
    image: postgres:latest
    container_name: mbdb
    environment:
      - POSTGRES_DB=mbdb
      - POSTGRES_USER=staff
      - POSTGRES_PASSWORD=happybeer
    volumes:
      - db_data_metabase:/var/lib/postgresql/data:cached
    ports:
      - 5432:5432
    restart: always
  mb:
    image: metabase/metabase:latest
    container_name: mb
    ports:
      - 80:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=mbdb
      - MB_DB_PORT=5432
      - MB_DB_USER=staff
      - MB_DB_PASS=happybeer
      - MB_DB_HOST=mbdb
    depends_on:
      - mbdb

volumes:
  db_data_bi:
    driver: local
  db_data_metabase:
    driver: local